author,number,labels,title,state,date,body,URL,closed_at,trace_links,files_changed,comments_authors,comments
pw96pw96pw96,4,,"Unable to find ""(Web/Contract Details)""",closed,2017-11-28 03:32:42,"In the alpha release documentation, there is a step to ""Create a call option"". (Web/Contract Details), according to the instruction, means when visiting ""https://alpha.zenprotocol.com/"", there should be a tab called ""Contract Details"". However, I am unable to find such a tab on the website. Perhaps I missed something? Thank you very much for your time. :)",https://github.com/zenprotocol/zen-wallet/issues/4,2017-11-28T03:32:42Z,,,, Found it after watching a youtube video :)
pw96pw96pw96,3,,Error out when trying to get test Zens from Faucet,closed,2017-11-20 17:42:23,"Go to https://alpha.zenprotocol.com/Faucet, enter my address 1QijnRSLm+dQOFKrlWPr17qqfwa8YE9xBawBrGKkC30I=
Click 'submit'. It errors out after 20 seconds. Further more, the url was then redirected to https://alpha.zenprotocol.com/Faucet/GetTokens, If I directly visit https://alpha.zenprotocol.com/Faucet/GetTokens, the stacktrace is exposed as:
System.Web.HttpException
The resource cannot be found.

Description: HTTP 404.The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable. Please review the following URL and make sure that it is spelled correctly.
Details: No virtual path information available.
Exception stack trace:
  at System.Web.Mvc.Controller.HandleUnknownAction (System.String actionName) [0x0006b] in <cc73190bab9d435c831510ff295c572a>:0 
  at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d (System.IAsyncResult asyncResult, System.Web.Mvc.Controller+ExecuteCoreState innerState) [0x0000f] in <cc73190bab9d435c831510ff295c572a>:0 
  at (wrapper delegate-invoke) System.Web.Mvc.Async.EndInvokeVoidDelegate`1[System.Web.Mvc.Controller+ExecuteCoreState]:invoke_void_IAsyncResult_TState (System.IAsyncResult,System.Web.Mvc.Controller/ExecuteCoreState)
  at System.Web.Mvc.Async.AsyncResultWrapper+WrappedAsyncVoid`1[TState].CallEndDelegate (System.IAsyncResult asyncResult) [0x00000] in <cc73190bab9d435c831510ff295c572a>:0 
  at System.Web.Mvc.Async.AsyncResultWrapper+WrappedAsyncResultBase`1[TResult].End () [0x00029] in <cc73190bab9d435c831510ff295c572a>:0 
  at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult] (System.IAsyncResult asyncResult, System.Object tag) [0x00007] in <cc73190bab9d435c831510ff295c572a>:0 
  at System.Web.Mvc.Async.AsyncResultWrapper.End (System.IAsyncResult asyncResult, System.Object tag) [0x00000] in <cc73190bab9d435c831510ff295c572a>:0 
  at System.Web.Mvc.Controller.EndExecuteCore (System.IAsyncResult asyncResult) [0x00000] in <cc73190bab9d435c831510ff295c572a>:0 
  at System.Web.Mvc.Controller.<BeginExecute>b__15 (System.IAsyncResult asyncResult, System.Web.Mvc.Controller controller) [0x00000] in <cc73190bab9d435c831510ff295c572a>:0 
  at System.Web.Mvc.Async.AsyncResultWrapper+WrappedAsyncVoid`1[TState].CallEndDelegate (System.IAsyncResult asyncResult) [0x00000] in <cc73190bab9d435c831510ff295c572a>:0 
  at System.Web.Mvc.Async.AsyncResultWrapper+WrappedAsyncResultBase`1[TResult].End () [0x00029] in <cc73190bab9d435c831510ff295c572a>:0 
  at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult] (System.IAsyncResult asyncResult, System.Object tag) [0x00007] in <cc73190bab9d435c831510ff295c572a>:0 
  at System.Web.Mvc.Async.AsyncResultWrapper.End (System.IAsyncResult asyncResult, System.Object tag) [0x00000] in <cc73190bab9d435c831510ff295c572a>:0 
  at System.Web.Mvc.Controller.EndExecute (System.IAsyncResult asyncResult) [0x00000] in <cc73190bab9d435c831510ff295c572a>:0 
  at System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute (System.IAsyncResult asyncResult) [0x00000] in <cc73190bab9d435c831510ff295c572a>:0 
  at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5 (System.IAsyncResult asyncResult, System.Web.Mvc.MvcHandler+ProcessRequestState innerState) [0x00000] in <cc73190bab9d435c831510ff295c572a>:0 
  at (wrapper delegate-invoke) System.Web.Mvc.Async.EndInvokeVoidDelegate`1[System.Web.Mvc.MvcHandler+ProcessRequestState]:invoke_void_IAsyncResult_TState (System.IAsyncResult,System.Web.Mvc.MvcHandler/ProcessRequestState)
  at System.Web.Mvc.Async.AsyncResultWrapper+WrappedAsyncVoid`1[TState].CallEndDelegate (System.IAsyncResult asyncResult) [0x00000] in <cc73190bab9d435c831510ff295c572a>:0 
  at System.Web.Mvc.Async.AsyncResultWrapper+WrappedAsyncResultBase`1[TResult].End () [0x00029] in <cc73190bab9d435c831510ff295c572a>:0 
  at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult] (System.IAsyncResult asyncResult, System.Object tag) [0x00007] in <cc73190bab9d435c831510ff295c572a>:0 
  at System.Web.Mvc.Async.AsyncResultWrapper.End (System.IAsyncResult asyncResult, System.Object tag) [0x00000] in <cc73190bab9d435c831510ff295c572a>:0 
  at System.Web.Mvc.MvcHandler.EndProcessRequest (System.IAsyncResult asyncResult) [0x00000] in <cc73190bab9d435c831510ff295c572a>:0 
  at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest (System.IAsyncResult result) [0x00000] in <cc73190bab9d435c831510ff295c572a>:0 
  at System.Web.HttpApplication.async_handler_complete_cb (System.IAsyncResult ar) [0x00015] in <347f335902b24586a53361aa1278a360>:0 
Version Information: 5.4.0.201 (tarball Fri Oct 13 21:51:45 UTC 2017); ASP.NET Version: 4.0.30319.42000",https://github.com/zenprotocol/zen-wallet/issues/3,2017-11-20T17:42:23Z,,,," firstly the 404 you're getting is due to the fact that the ASP.Net MVC controller is not designed to handle GET requests directly, and second - we were having some trouble with the faucet after it was DOS attacked :)
it should be working now. Yes, it indeed works now. Thank you.:)"
victorjof,12,,Uncaught Exception in zenwallet install,open,,"When tryinging to run the executable i get the following error. Ubuntu 16.04, zenwalletv0.9.69
 
> A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Malformed JSON in file: /home/user/.config/zenwallet/zen-wallet-db.json
Unexpected string in JSON at position 2460
    at n.parse [as deserialize] (<anonymous>)
    at n.value (/home/user/Downloads/zen-wallet-0.9.67/resources/app.asar/main.prod.js:1:167213)
    at gi.t.read (/home/user/Downloads/zen-wallet-0.9.67/resources/app.asar/main.prod.js:1:168079)
    at e.exports (/home/user/Downloads/zen-wallet-0.9.67/resources/app.asar/main.prod.js:1:168288)
    at Object../app/services/db.js (/home/user/Downloads/zen-wallet-0.9.67/resources/app.asar/main.prod.js:1:10551)
    at t (/home/user/Downloads/zen-wallet-0.9.67/resources/app.asar/main.prod.js:1:279)
    at Object../app/ZenNode.js (/home/user/Downloads/zen-wallet-0.9.67/resources/app.asar/main.prod.js:1:1367)
    at t (/home/user/Downloads/zen-wallet-0.9.67/resources/app.asar/main.prod.js:1:279)
    at Object../app/main.dev.js (/home/user/Downloads/zen-wallet-0.9.67/resources/app.asar/main.prod.js:1:7319)
    at t (mypath/zen-wallet-0.9.67/resources/app.asar/main.prod.js:1:279)",https://github.com/zenprotocol/zen-wallet/issues/12,,,,,
paulwehner,11,,Error - Unhandled exception wallet System.Exception: Could not handle GetAddressPKHash ,open,,"When following the tutorial, and you run:

zen-wallet wipe mine

I get the following error:

Error - Unhandled exception wallet System.Exception: Could not handle GetAddressPKHash ",https://github.com/zenprotocol/zen-wallet/issues/11,,,,,
CyberCyclone,10,,Block stuck at 1/783,open,,"I'm just wondering if there's an obvious reason as to why I can download the blockchain and when it reaches 782/783, it resets back to 1/783 and then stays there? The console logs below are all it produces. I've left it overnight several times and reset the blockchain numerous times.

I'm running Ubuntu 17.10 and Zen wallet is the latest alpha version.

Network(I) Sending PingPayload to 35.163.150.86                          
   Network(V) Receiving VersionPayload from 34.213.103.167                  
   Network(I) Sending PingPayload to 52.42.204.73                           
   Network(V) Receiving PingPayload from 54.218.16.136                      
   Network(I) Sending PongPayload to 54.218.16.136                          
   Network(V) Receiving PongPayload from 52.42.204.73                       
Network(V) Receiving PongPayload from 54.218.16.136                      
Network(V) Receiving PingPayload from 52.42.204.73                       
Network(I) Sending PongPayload to 52.42.204.73                           
Network(I) Sending PingPayload to 34.213.103.167                         
  Network(V) Receiving PongPayload from 34.213.103.167                     
  Network(V) Receiving PingPayload from 34.213.103.167                     
  Network(I) Sending PongPayload to 34.213.103.167               ",https://github.com/zenprotocol/zen-wallet/issues/10,,,,,
mattisback,9,,System.TypeInitializationException on ubuntu,open,,"I followed the steps to run the wallet on ubuntu but ran into the following error:

```

 **$$* Node starting with args: 


Unhandled Exception:
System.TypeInitializationException: The type initializer for 'Consensus.Tests' threw an exception. ---> System.TypeInitializationException: The type initializer for '<StartupCode$Consensus>.$Consensus.Tests' threw an exception. ---> System.MissingMethodException: Method 'DateTimeOffset.ToUnixTimeSeconds' not found.
  --- End of inner exception stack trace ---
  at Consensus.Tests..cctor () <0x411cff20 + 0x0000b> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Zen.App.get_GenesisBlock () <0x411c8960 + 0x00333> in <filename unknown>:0 
  at Zen.App.get_AppBlockChain () <0x411c86a0 + 0x0005b> in <filename unknown>:0 
  at Zen.App.get_WalletManager () <0x411c8600 + 0x0001f> in <filename unknown>:0 
  at Zen.App.Init () <0x411c85c0 + 0x0000f> in <filename unknown>:0 
  at Zen.Program.Init (Boolean connect) <0x411c8380 + 0x0006b> in <filename unknown>:0 
  at Zen.Program.Main (System.String[] args) <0x4114a000 + 0x00b47> in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'Consensus.Tests' threw an exception. ---> System.TypeInitializationException: The type initializer for '<StartupCode$Consensus>.$Consensus.Tests' threw an exception. ---> System.MissingMethodException: Method 'DateTimeOffset.ToUnixTimeSeconds' not found.
  --- End of inner exception stack trace ---
  at Consensus.Tests..cctor () <0x411cff20 + 0x0000b> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Zen.App.get_GenesisBlock () <0x411c8960 + 0x00333> in <filename unknown>:0 
  at Zen.App.get_AppBlockChain () <0x411c86a0 + 0x0005b> in <filename unknown>:0 
  at Zen.App.get_WalletManager () <0x411c8600 + 0x0001f> in <filename unknown>:0 
  at Zen.App.Init () <0x411c85c0 + 0x0000f> in <filename unknown>:0 
  at Zen.Program.Init (Boolean connect) <0x411c8380 + 0x0006b> in <filename unknown>:0 
  at Zen.Program.Main (System.String[] args) <0x4114a000 + 0x00b47> in <filename unknown>:0 
```

I'm running
`Linux version 4.4.0-101-generic (buildd@lcy01-amd64-006) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) ) #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017`

Something to do with `Method 'DateTimeOffset.ToUnixTimeSeconds' not found.`?  Could this be something to do with missing .NET functions?
",https://github.com/zenprotocol/zen-wallet/issues/9,,['124'],,,
ilya-fiveisky,8,,"""Not enough Zen"" on call option activation",open,,"When I try to activate call option in Zen wallet (on Ubuntu 16.04) I get `Not enough Zen` message (see screenshot) though I have 50000000 balance.

![screenshot from 2017-12-06 17-19-36](https://user-images.githubusercontent.com/4052190/33683791-e183a18a-daaa-11e7-8eb9-efce40d97e8e.png)
",https://github.com/zenprotocol/zen-wallet/issues/8,,,,,
ilya-fiveisky,7,,Unable to load DLL 'libglib-2.0-0.dll',open,,"When I try to start Zen wallet (on Windows 8.1) I get in console the following text with error
> 
>  ***** Node starting with args:
> 
> BlockChain(I) No tip.
> Network(I) Magic is 1
> Network(I) Warning, found 2 internal addresses
> Network(W) Remaining peers to get : 10
> System.DllNotFoundException: Unable to load DLL 'libglib-2.0-0.dll': The specifi
> ed module could not be found. (Exception from HRESULT: 0x8007007E)
>    at GLib.Marshaller.g_malloc(UIntPtr size)
>    at GLib.Marshaller.StringToPtrGStrdup(String str)
>    at GLib.Global.set_ProgramName(String value)
>    at Gtk.Application.SetPrgname()
>    at Gtk.Application.Init()
>    at Wallet.App.Start(WalletManager walletManager, NodeManager nodeManager)
>    at Zen.App.GUI(Boolean shutdownOnClose)
>    at Zen.Program.Main(String[] args)
> 
> Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libglib-2.
> 0-0.dll': The specified module could not be found. (Exception from HRESULT: 0x80
> 07007E)
>    at GLib.Marshaller.g_malloc(UIntPtr size)
>    at GLib.Marshaller.StringToPtrGStrdup(String str)
>    at GLib.Global.set_ProgramName(String value)
>    at Gtk.Application.SetPrgname()
>    at Gtk.Application.Init()
>    at Wallet.App.Start(WalletManager walletManager, NodeManager nodeManager)
>    at Zen.App.GUI(Boolean shutdownOnClose)
>    at Zen.Program.Main(String[] args)
> ",https://github.com/zenprotocol/zen-wallet/issues/7,,,,, Workaround - install  [Gtk#](https://dl.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.45.msi)
pw96pw96pw96,6,,TransactionValidation.fs does not need to verify the 'bounds' of a contract?,open,,"According the zen protocol's white paper, contract 'bounds' represents the amount of computation needed to run the F* program. If a miner receives a transaction containing a contract which declares a very small number for bounds, but in fact has a very large number for bounds, the miner will be tricked to prioritize such a transaction (if the transaction validation does not validate the bounds)???",https://github.com/zenprotocol/zen-wallet/issues/6,,,,,
gsdean,2,triaged,Discovery error with peer: NBitcoin.Protocol.NetworkAddress OperationCanceledException: The operation was canceled,open,,"following the instructions for OSX (https://www.zenprotocol.com/alpha).

Full Stack:
Network(E) Discovery error with peer: NBitcoin.Protocol.NetworkAddress OperationCanceledException: The operation was canceled.  at System.Collections.Concurrent.BlockingCollection`1[T].TryTakeWithNoTimeValidation (T& item, System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken, System.Threading.CancellationTokenSource combinedTokenSource) [0x0008e] in <5afdc70d980c4033b3878286f754d091>:0 
  at System.Collections.Concurrent.BlockingCollection`1[T].TryTake (T& item, System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00006] in <5afdc70d980c4033b3878286f754d091>:0 
  at System.Collections.Concurrent.BlockingCollection`1[T].Take (System.Threading.CancellationToken cancellationToken) [0x00000] in <5afdc70d980c4033b3878286f754d091>:0 
  at NBitcoin.Protocol.PollMessageListener`1[T].ReceiveMessage (System.Threading.CancellationToken cancellationToken) [0x00006] in <c79239f051444075b68b7920aba1b848>:0 
  at NBitcoin.Protocol.NodeListener.ReceivePayload[TPayload] (System.Threading.CancellationToken cancellationToken) [0x000d1] in <c79239f051444075b68b7920aba1b848>:0 
  at NBitcoin.Protocol.Node.VersionHandshake (NBitcoin.Protocol.NodeRequirement requirements, System.Threading.CancellationToken cancellationToken) [0x00044] in <c79239f051444075b68b7920aba1b848>:0 
  at NBitcoin.Protocol.Node.VersionHandshake (System.Threading.CancellationToken cancellationToken) [0x00000] in <c79239f051444075b68b7920aba1b848>:0 
  at NBitcoin.Protocol.AddressManager+<>c__DisplayClass70_0.<DiscoverPeers>b__1 (NBitcoin.Protocol.NetworkAddress p) [0x00086] in <c79239f051444075b68b7920aba1b848>:0",https://github.com/zenprotocol/zen-wallet/issues/2,,,,," Thanks. We're overhauling the network code, which should fix this bug. We've restarted the seed peers so you should be able to connect in the mean time. got the same issue here The app started back to connect got the same issue here here is the same error  The app could connect to peer now, though it still generated an error msg beforehand:
Network(E) Error while OnMessageReceived event raised SocketException: Operation not supported  at System.Net.IPAddress.get_Address () [0x00014] in <a24e193d5cf14a42ac00ebaea26ec7bc>:0 
  at NBitcoin.Protocol.AddressManager.ContainsAddress (System.Net.IPAddress address) [0x0001a] in <bb37feab734942c999a26765ef4da255>:0 
  at NBitcoin.Protocol.AddressManager.Add (System.Collections.Generic.IEnumerable`1[T] vAddr, System.Net.IPAddress source, System.TimeSpan nTimePenalty) [0x00037] in <bb37feab734942c999a26765ef4da255>:0 
  at NBitcoin.Protocol.AddressManager.Add (System.Collections.Generic.IEnumerable`1[T] vAddr, System.Net.IPAddress source) [0x00011] in <bb37feab734942c999a26765ef4da255>:0 
  at NBitcoin.Protocol.Behaviors.AddressManagerBehavior+<>c__DisplayClass16_0.<AttachedNode_MessageReceived>b__2 (NBitcoin.Protocol.AddrPayload addr) [0x00081] in <bb37feab734942c999a26765ef4da255>:0 
  at NBitcoin.Protocol.Message.IfPayloadIs[T] (System.Action`1[T] action) [0x00019] in <bb37feab734942c999a26765ef4da255>:0 
  at NBitcoin.Protocol.Behaviors.AddressManagerBehavior.AttachedNode_MessageReceived (NBitcoin.Protocol.Node node, NBitcoin.Protocol.IncomingMessage message) [0x0003b] in <bb37feab734942c999a26765ef4da255>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
I guess it might just be timing issue: the depended service didn't start the first time, then it started, and thus connection is ok... ```
Network Information: 0 : Disconnection request 
Network Information: 0 : State changed from Connected to Disconnecting
Network Information: 0 : Need 1 more peers
Network Information: 0 : Stop sending
Network Information: 0 : State changed from Disconnecting to Offline
Network Information: 0 : Stop listening
Network Information: 0 : Remaining peer to get : 1
Network Information: 0 : State changed from Offline to Connected
Network Information: 0 : Outbound connection successfull
Network Information: 0 : Listening
Network Error: 0 : Discovery error with peer: NBitcoin.Protocol.NetworkAddress OperationCanceledException: The operation was canceled.  at System.Collections.Concurrent.BlockingCollection`1[T].TryTakeWithNoTimeValidation (T& item, System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken, System.Threading.CancellationTokenSource combinedTokenSource) [0x0008e] in <5afdc70d980c4033b3878286f754d091>:0 
  at System.Collections.Concurrent.BlockingCollection`1[T].TryTake (T& item, System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00006] in <5afdc70d980c4033b3878286f754d091>:0 
  at System.Collections.Concurrent.BlockingCollection`1[T].Take (System.Threading.CancellationToken cancellationToken) [0x00000] in <5afdc70d980c4033b3878286f754d091>:0 
  at NBitcoin.Protocol.PollMessageListener`1[T].ReceiveMessage (System.Threading.CancellationToken cancellationToken) [0x00006] in <c79239f051444075b68b7920aba1b848>:0 
  at NBitcoin.Protocol.NodeListener.ReceivePayload[TPayload] (System.Threading.CancellationToken cancellationToken) [0x000d1] in <c79239f051444075b68b7920aba1b848>:0 
  at NBitcoin.Protocol.Node.VersionHandshake (NBitcoin.Protocol.NodeRequirement requirements, System.Threading.CancellationToken cancellationToken) [0x00044] in <c79239f051444075b68b7920aba1b848>:0 
  at NBitcoin.Protocol.Node.VersionHandshake (System.Threading.CancellationToken cancellationToken) [0x00000] in <c79239f051444075b68b7920aba1b848>:0 
  at NBitcoin.Protocol.AddressManager+<>c__DisplayClass70_0.<DiscoverPeers>b__1 (NBitcoin.Protocol.NetworkAddress p) [0x00086] in <c79239f051444075b68b7920aba1b848>:0 
```
I notify when you open the app it's allwayse fail to get the connection. But after a time X it will successed connect @pw96pw96pw96 - new binaries are available for download which should fix the issue you encountered @Douvi this is not actually a bug or an error, it's just that the trace shouldn't be printing that. it's printed when a connection cant be established with a peer that's listed in the node's address list @UrbanSharon - It will be helpful if instructions on how to build and run from source could be given. Anyway, thank you for fixing the issue.   @UrbanSharon I sent some Zen via the faucet into address 14eh93uk/Nfogl/NiyHVpwzxCXPz6Z8kv/CRMFVzaCr0=. But when I opened the wallet/portfolio, it says ""Discovering peers: 0%"" See screenshot. My node started via mono zen.exe -m is running fine.
![screen shot 2017-11-20 at 3 42 22 pm](https://user-images.githubusercontent.com/20891594/33047265-b915147a-ce09-11e7-9b06-7b0455a99aa5.png)
 @UrbanSharon After leaving the wallet open for a long time, it can show the balance now. I guess it was because the wallet was downloading all the blocks. Issue resolved. Thx."
